### ISSUE TITLE
Exception while loading plugin flexget.plugins.auto_sign_in

### ISSUE THREAD

**Issue by sjq597** [lhllhx/PT_signin#11]
签到出错了这个是代码版本更新的原因吗

2022-05-25 20:07:03 DEBUG    manager                       Figuring out config load paths
2022-05-25 20:07:03 DEBUG    manager                       Found config: /home/runner/.flexget/config.yml
2022-05-25 20:07:03 DEBUG    manager                       Config file /home/runner/.flexget/config.yml selected
2022-05-25 20:07:03 DEBUG    manager                       sys.defaultencoding: utf-8
2022-05-25 20:07:03 DEBUG    manager                       sys.getfilesystemencoding: utf-8
2022-05-25 20:07:03 DEBUG    manager                       flexget detected io encoding: utf-8
2022-05-25 20:07:03 DEBUG    manager                       os.path.supports_unicode_filenames: False
2022-05-25 20:07:03 DEBUG    plugin                        Trying to load plugins from: ['/home/runner/.flexget/plugins', '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/flexget/plugins']
2022-05-25 20:07:03 CRITICAL plugin                        Exception while loading plugin flexget.plugins.auto_sign_in
Traceback (most recent call last):

  File "/opt/hostedtoolcache/Python/3.8.12/x64/bin/flexget", line 8, in <module>
    sys.exit(main())
    │   │    └ <function main at 0x7fd0b6a27af0>
    │   └ <built-in function exit>
    └ <module 'sys' (built-in)>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/flexget/__init__.py", line 44, in main
    manager.start()
    │       └ <function Manager.start at 0x7fd0ae5f3e50>
    └ <flexget.manager.Manager object at 0x7fd0ae5f7250>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/flexget/manager.py", line 382, in start
    self.initialize()
    │    └ <function Manager.initialize at 0x7fd0ae5f3c10>
    └ <flexget.manager.Manager object at 0x7fd0ae5f7250>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/flexget/manager.py", line 224, in initialize
    plugin.load_plugins(
    │      └ <function load_plugins at 0x7fd0aecfb310>
    └ <module 'flexget.plugin' from '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/flexget/plugin.py'>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/flexget/plugin.py", line 550, in load_plugins
    _load_plugins_from_dirs(extra_plugins)
    │                       └ ['/home/runner/.flexget/plugins', '/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/flexget/plugins']
    └ <function _load_plugins_from_dirs at 0x7fd0aecfb5e0>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/flexget/plugin.py", line 468, in _load_plugins_from_dirs
    _import_plugin(module_name, plugin_path)
    │              │            └ PosixPath('/home/runner/.flexget/plugins/auto_sign_in.py')
    │              └ 'flexget.plugins.auto_sign_in'
    └ <function _import_plugin at 0x7fd0aecfb040>
> File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/flexget/plugin.py", line 419, in _import_plugin
    import_module(module_name)
    │             └ 'flexget.plugins.auto_sign_in'
    └ <function import_module at 0x7fd0b6cff040>
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'flexget.plugins.auto_sign_in'
           │          └ <function _gcd_import at 0x7fd0b6e29430>
           └ <module 'importlib._bootstrap' (frozen)>
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/home/runner/.flexget/plugins/auto_sign_in.py", line 10, in <module>
    from .ptsites import executor

  File "/home/runner/.flexget/plugins/ptsites/executor.py", line 9, in <module>
    from .base.sign_in import sign_in

  File "/home/runner/.flexget/plugins/ptsites/base/sign_in.py", line 6, in <module>
    from .base import Work

  File "/home/runner/.flexget/plugins/ptsites/base/base.py", line 27, in <module>
    class Work:

  File "/home/runner/.flexget/plugins/ptsites/base/base.py", line 29, in Work
    succeed_regex: Union[list[Union[str, tuple]], tuple[str, int]] = None, fail_regex: str = None,
                   │          └ typing.Union
                   └ typing.Union

TypeError: 'type' object is not subscriptable
2022-05-25 20:07:03 DEBUG    manager                       Removed /home/runner/.flexget/.config-lock

**Comment by lhllhx** [comment]
是 重新fork或者 自己pr一下更新

**Comment by sjq597** [comment]
昨天更新了重跑了几次不行，今天定时的任务成功了

**Comment by lhllhx** [comment]
上游项目最近更新比较频繁 有可能会有bug
